# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ConnectionToMainDatabaseDialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConnectionToMainDatabaseDialog(object):
    def setupUi(self, ConnectionToMainDatabaseDialog):
        ConnectionToMainDatabaseDialog.setObjectName("ConnectionToMainDatabaseDialog")
        ConnectionToMainDatabaseDialog.resize(320, 310)
        ConnectionToMainDatabaseDialog.setMinimumSize(QtCore.QSize(320, 310))
        ConnectionToMainDatabaseDialog.setMaximumSize(QtCore.QSize(320, 310))
        ConnectionToMainDatabaseDialog.setBaseSize(QtCore.QSize(320, 310))
        self.server_name_edit = QtWidgets.QLineEdit(ConnectionToMainDatabaseDialog)
        self.server_name_edit.setGeometry(QtCore.QRect(60, 56, 200, 20))
        self.server_name_edit.setObjectName("server_name_edit")
        self.port_edit = QtWidgets.QLineEdit(ConnectionToMainDatabaseDialog)
        self.port_edit.setGeometry(QtCore.QRect(60, 96, 200, 20))
        self.port_edit.setObjectName("port_edit")
        self.database_edit = QtWidgets.QLineEdit(ConnectionToMainDatabaseDialog)
        self.database_edit.setGeometry(QtCore.QRect(60, 136, 200, 20))
        self.database_edit.setObjectName("database_edit")
        self.user_name_edit = QtWidgets.QLineEdit(ConnectionToMainDatabaseDialog)
        self.user_name_edit.setGeometry(QtCore.QRect(60, 176, 200, 20))
        self.user_name_edit.setObjectName("user_name_edit")
        self.label = QtWidgets.QLabel(ConnectionToMainDatabaseDialog)
        self.label.setGeometry(QtCore.QRect(60, 36, 200, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ConnectionToMainDatabaseDialog)
        self.label_2.setGeometry(QtCore.QRect(60, 76, 200, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ConnectionToMainDatabaseDialog)
        self.label_3.setGeometry(QtCore.QRect(60, 116, 200, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ConnectionToMainDatabaseDialog)
        self.label_4.setGeometry(QtCore.QRect(60, 156, 200, 17))
        self.label_4.setObjectName("label_4")
        self.ok_button = QtWidgets.QPushButton(ConnectionToMainDatabaseDialog)
        self.ok_button.setGeometry(QtCore.QRect(153, 265, 70, 23))
        self.ok_button.setObjectName("ok_button")
        self.cancel_button = QtWidgets.QPushButton(ConnectionToMainDatabaseDialog)
        self.cancel_button.setGeometry(QtCore.QRect(230, 265, 70, 23))
        self.cancel_button.setObjectName("cancel_button")
        self.line = QtWidgets.QFrame(ConnectionToMainDatabaseDialog)
        self.line.setGeometry(QtCore.QRect(0, 20, 321, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(ConnectionToMainDatabaseDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 290, 321, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtWidgets.QLabel(ConnectionToMainDatabaseDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 371, 17))
        self.label_5.setObjectName("label_5")
        self.help_button = QtWidgets.QPushButton(ConnectionToMainDatabaseDialog)
        self.help_button.setGeometry(QtCore.QRect(110, 265, 30, 23))
        self.help_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/lm2/help_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_button.setIcon(icon)
        self.help_button.setObjectName("help_button")
        self.password_edit = QtWidgets.QLineEdit(ConnectionToMainDatabaseDialog)
        self.password_edit.setGeometry(QtCore.QRect(60, 216, 200, 20))
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.label_6 = QtWidgets.QLabel(ConnectionToMainDatabaseDialog)
        self.label_6.setGeometry(QtCore.QRect(60, 196, 200, 16))
        self.label_6.setObjectName("label_6")
        self.error_label = QtWidgets.QLabel(ConnectionToMainDatabaseDialog)
        self.error_label.setGeometry(QtCore.QRect(20, 240, 291, 16))
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.connect_label = QtWidgets.QLabel(ConnectionToMainDatabaseDialog)
        self.connect_label.setGeometry(QtCore.QRect(60, 240, 241, 16))
        self.connect_label.setText("")
        self.connect_label.setObjectName("connect_label")

        self.retranslateUi(ConnectionToMainDatabaseDialog)
        QtCore.QMetaObject.connectSlotsByName(ConnectionToMainDatabaseDialog)
        ConnectionToMainDatabaseDialog.setTabOrder(self.server_name_edit, self.port_edit)
        ConnectionToMainDatabaseDialog.setTabOrder(self.port_edit, self.database_edit)
        ConnectionToMainDatabaseDialog.setTabOrder(self.database_edit, self.user_name_edit)
        ConnectionToMainDatabaseDialog.setTabOrder(self.user_name_edit, self.password_edit)
        ConnectionToMainDatabaseDialog.setTabOrder(self.password_edit, self.ok_button)
        ConnectionToMainDatabaseDialog.setTabOrder(self.ok_button, self.help_button)
        ConnectionToMainDatabaseDialog.setTabOrder(self.help_button, self.cancel_button)

    def retranslateUi(self, ConnectionToMainDatabaseDialog):
        _translate = QtCore.QCoreApplication.translate
        ConnectionToMainDatabaseDialog.setWindowTitle(_translate("ConnectionToMainDatabaseDialog", "Dialog"))
        self.label.setText(_translate("ConnectionToMainDatabaseDialog", "Server Name / IP Address"))
        self.label_2.setText(_translate("ConnectionToMainDatabaseDialog", "Port"))
        self.label_3.setText(_translate("ConnectionToMainDatabaseDialog", "Database"))
        self.label_4.setText(_translate("ConnectionToMainDatabaseDialog", "User Name"))
        self.ok_button.setText(_translate("ConnectionToMainDatabaseDialog", "Ok"))
        self.cancel_button.setText(_translate("ConnectionToMainDatabaseDialog", "Cancel"))
        self.label_5.setText(_translate("ConnectionToMainDatabaseDialog", "Connection To Main Database (Working DB)"))
        self.label_6.setText(_translate("ConnectionToMainDatabaseDialog", "Password"))
